ENT.Type = "vehicle"
ENT.Base = "base_anim"
ENT.PrintName	= "AV-8B Harrier"
ENT.Author	= "Hoffa"
ENT.Category 		= "NeuroTec Aviation";
ENT.Spawnable	= true
ENT.AdminSpawnable = false
ENT.VehicleType = VEHICLE_PLANE
ENT.HasAfterburner = false
ENT.HasAirbrakes = false