ENT.Type = "anim"
ENT.Base = "base_anim"
ENT.PrintName	= "Phalanx CIWS"
ENT.Author	= "Hoffa,StarChick,Sillirion"
ENT.Description = "Vulcan turret"
ENT.Category 		= "NeuroTec Weapons";
ENT.Spawnable	= true
ENT.AdminSpawnable = false
ENT.VehicleType = WEAPON_TURRET