ENT.Type = "vehicle"
ENT.Base = "base_anim"
ENT.PrintName	= "B-17 Flying Fortress"
ENT.Author	= "Hoffa/StarChick"
ENT.Category 		= "NeuroTec Warbirds";
ENT.Spawnable	= true
ENT.AdminSpawnable = false
ENT.VehicleType = VEHICLE_WARBIRD
ENT.HasAfterburner = false
ENT.HasAirbrakes = false