ENT.Type = "vehicle"
ENT.Base = "base_anim"
ENT.PrintName	= "ZSU-23-4 Shilka AA"
ENT.Author	= "Hoffa"
ENT.Category 		= "NeuroTec - Anti-Air Vehicles";
ENT.Spawnable	= true
ENT.AdminSpawnable = true
ENT.VehicleType = VEHICLE_TANK
ENT.TankType = TANK_TYPE_AA
ENT.HasBinoculars = true
ENT.VehicleCrosshairType = 1 -- Small
ENT.BarrelLength = 100