ENT.Type = "vehicle"
ENT.Base = "base_anim"
ENT.PrintName	= "Supermarine Spitfire"
ENT.Author	= "Hoffa, StarChick, Silliron"
ENT.Category 		= "NeuroTec Warbirds";
ENT.Spawnable	= true
ENT.AdminSpawnable = false
ENT.VehicleType = VEHICLE_WARBIRD
ENT.HasAfterburner = false
ENT.HasAirbrakes = false