ENT.Type = "vehicle"
ENT.Base = "base_anim"
ENT.PrintName	= "AC-47 Skytrain"
ENT.Author	= "Hoffa"
ENT.Category 		= "NeuroTec Aviation";
ENT.Description = "Requires a gun crew"
ENT.Spawnable	= true
ENT.AdminSpawnable = false
ENT.VehicleType = VEHICLE_WARBIRD
ENT.HasAfterburner = false
ENT.HasAirbrakes = false