TANK_LIGHT_DAMAGE_SHELL_MIN = 450
TANK_LIGHT_DAMAGE_SHELL_MAX = 750
TANK_LIGHT_DAMAGE_APSHELL_MIN = 650
TANK_LIGHT_DAMAGE_APSHELL_MAX = 850
TANK_LIGHT_DAMAGE_APRADIUS = 80
TANK_LIGHT_DAMAGE_RADIUS = 100

TANK_MEDIUM_DAMAGE_SHELL_MIN = 600
TANK_MEDIUM_DAMAGE_SHELL_MAX = 1200
TANK_MEDIUM_DAMAGE_APSHELL_MIN = 650
TANK_MEDIUM_DAMAGE_APSHELL_MAX = 1400
TANK_MEDIUM_DAMAGE_APRADIUS = 102
TANK_MEDIUM_DAMAGE_RADIUS = 160

TANK_HEAVY_DAMAGE_SHELL_MIN = 1050
TANK_HEAVY_DAMAGE_SHELL_MAX = 2000
TANK_HEAVY_DAMAGE_APSHELL_MIN = 950
TANK_HEAVY_DAMAGE_APSHELL_MAX = 1750
TANK_HEAVY_DAMAGE_APRADIUS = 128
TANK_HEAVY_DAMAGE_RADIUS = 256

TANK_SUPERHEAVY_DAMAGE_SHELL_MIN = 2050
TANK_SUPERHEAVY_DAMAGE_SHELL_MAX = 2500
TANK_SUPERHEAVY_DAMAGE_APSHELL_MIN = 2250
TANK_SUPERHEAVY_DAMAGE_APSHELL_MAX = 3150
TANK_SUPERHEAVY_DAMAGE_APRADIUS = 228
TANK_SUPERHEAVY_DAMAGE_RADIUS = 356

TANK_ARTILLERY_DAMAGE_SHELL_MIN = 3550
TANK_ARTILLERY_DAMAGE_SHELL_MAX = 5500
TANK_ARTILLERY_DAMAGE_APSHELL_MIN = 3250
TANK_ARTILLERY_DAMAGE_APSHELL_MAX = 4550
TANK_ARTILLERY_DAMAGE_APRADIUS = 512
TANK_ARTILLERY_DAMAGE_RADIUS = 956

TANK_EQUIPMENT_NONE = 0
TANK_EQUIPMENT_FLAMER = 1
TANK_EQUIPMENT_FLAIL = 2
TANK_EQUIPMENT_SHTORA = 4
TANK_EQUIPMENT_REACTIVE = 8
TANK_EQUIPMENT_RADAR = 16

TANK_TYPE_CAR = 1
TANK_TYPE_AA = TANK_TYPE_CAR + 1
TANK_TYPE_LIGHT = TANK_TYPE_AA+1
TANK_TYPE_MEDIUM = TANK_TYPE_LIGHT+1
TANK_TYPE_HEAVY = TANK_TYPE_MEDIUM+1
TANK_TYPE_ARTILLERY = TANK_TYPE_HEAVY+1
TANK_TYPE_SUPERHEAVY = TANK_TYPE_ARTILLERY+1

TANK_TYPE_MAX = TANK_TYPE_ARTILLERY + 1

-- Formula: DAMAGE = DAMAGE *  ( MODIFER - ARMORTHICKNESS )
TANK_DAMAGE_MODIFIER_FRONT = 1.0
TANK_DAMAGE_MODIFIER_SIDE = 1.15
TANK_DAMAGE_MODIFIER_REAR = 2.15

--DamageTables
NeuroTanksDamageTables = { 
							{ TANK_LIGHT_DAMAGE_SHELL_MIN, TANK_LIGHT_DAMAGE_SHELL_MAX, TANK_LIGHT_DAMAGE_APSHELL_MIN, TANK_LIGHT_DAMAGE_APSHELL_MAX, TANK_LIGHT_DAMAGE_APRADIUS, TANK_LIGHT_DAMAGE_RADIUS };
							{ TANK_LIGHT_DAMAGE_SHELL_MIN, TANK_LIGHT_DAMAGE_SHELL_MAX, TANK_LIGHT_DAMAGE_APSHELL_MIN, TANK_LIGHT_DAMAGE_APSHELL_MAX, TANK_LIGHT_DAMAGE_APRADIUS, TANK_LIGHT_DAMAGE_RADIUS };
							{ TANK_LIGHT_DAMAGE_SHELL_MIN, TANK_LIGHT_DAMAGE_SHELL_MAX, TANK_LIGHT_DAMAGE_APSHELL_MIN, TANK_LIGHT_DAMAGE_APSHELL_MAX, TANK_LIGHT_DAMAGE_APRADIUS, TANK_LIGHT_DAMAGE_RADIUS };
							{ TANK_MEDIUM_DAMAGE_SHELL_MIN, TANK_MEDIUM_DAMAGE_SHELL_MAX, TANK_MEDIUM_DAMAGE_APSHELL_MIN, TANK_MEDIUM_DAMAGE_APSHELL_MAX, TANK_MEDIUM_DAMAGE_APRADIUS, TANK_MEDIUM_DAMAGE_RADIUS };
							{ TANK_HEAVY_DAMAGE_SHELL_MIN, TANK_HEAVY_DAMAGE_SHELL_MAX, TANK_HEAVY_DAMAGE_APSHELL_MIN, TANK_HEAVY_DAMAGE_APSHELL_MAX, TANK_HEAVY_DAMAGE_APRADIUS, TANK_HEAVY_DAMAGE_RADIUS };
							{ TANK_SUPERHEAVY_DAMAGE_SHELL_MIN, TANK_SUPERHEAVY_DAMAGE_SHELL_MAX, TANK_SUPERHEAVY_DAMAGE_APSHELL_MIN, TANK_SUPERHEAVY_DAMAGE_APSHELL_MAX, TANK_SUPERHEAVY_DAMAGE_APRADIUS, TANK_SUPERHEAVY_DAMAGE_RADIUS };
							{ TANK_ARTILLERY_DAMAGE_SHELL_MIN, TANK_ARTILLERY_DAMAGE_SHELL_MAX, TANK_ARTILLERY_DAMAGE_APSHELL_MIN, TANK_ARTILLERY_DAMAGE_APSHELL_MAX, TANK_ARTILLERY_DAMAGE_APRADIUS, TANK_ARTILLERY_DAMAGE_RADIUS }; 
						 };	

print( "[NeuroTanks] tankdamagetables.lua loaded!" )