//Precaching stuff.
PrecacheParticleSystem("impact_concrete")
PrecacheParticleSystem("impact_metal")
PrecacheParticleSystem("impact_computer")
PrecacheParticleSystem("impact_grass")
PrecacheParticleSystem("impact_dirt")
PrecacheParticleSystem("impact_wood")
PrecacheParticleSystem("impact_glass")

function precachestuff()
	
	util.PrecacheModel("models/usmcapachehelicopter.mdl")
	util.PrecacheModel("models/ufo/ufo.mdl")
	util.PrecacheModel("models/neuroplanes/c-47 skytrain.mdl")
	util.PrecacheModel("models/bf2/helicopters/ah-1 cobra/ah-1 cobra.mdl")
	util.PrecacheModel("models/bf2/helicopters/ah-1 cobra/ah-1 cobra_cannon.mdl")
	util.PrecacheModel("models/bf2/helicopters/ah-1 cobra/ah-1 cobra_rotor.mdl")    //holy shit that took long
	util.PrecacheModel("models/bf2/helicopters/ah-1 cobra/ah-1 cobra_tail.mdl")
	util.PrecacheModel("models/bf2/helicopters/ah-1 cobra/ah-1 cobra_tail.mdl")
	util.PrecacheModel("models/bf2/helicopters/ah-2 rooivalk/ah-2 rooivalk.mdl")
	util.PrecacheModel("models/bf2/helicopters/ah-2 rooivalk/ah-2 rooivalk_rotor.mdl")
	util.PrecacheModel("models/bf2/helicopters/mh-53j pave low iiie/mh-53j.mdl")
	util.PrecacheModel("models/hawx/air/a-6 intruder.mdl")
	util.PrecacheModel("models/hawx/air/a-7 corsair ii")
	util.PrecacheModel("models/hawx/air/a-10 thunderbolt ii")
	util.PrecacheModel("models/hawx/air/dassault mirage 2000 n.mdl")
	util.PrecacheModel("models/hawx/air/dassault rafale m.mdl")
	util.PrecacheModel("models/hawx/air/f-4e phantom ii.mdl")
	util.PrecacheModel("models/hawx/air/f-14a tomcat.mdl..mdl")
	util.PrecacheModel("models/hawx/air/f-15c eagle.mdl")
	util.PrecacheModel("models/hawx/air/f-15 active.mdl")
	util.PrecacheModel("models/hawx/air/f-16a fighting falcon.mdl")
	util.PrecacheModel("models/hawx/air/f-35 lightning ii.mdl")
	util.PrecacheModel("models/hawx/air/f117 nighthawk.mdl")
	util.PrecacheModel("models/hawx/air/fa-22 raptor.mdl")
	util.PrecacheModel("models/hawx/air/mig-29 fulcrum.mdl")
	util.PrecacheModel("models/hawx/air/mig-mfi.mdl")
	util.PrecacheModel("models/hawx/air/su-47 berkut.mdl")
	util.PrecacheModel("models/hawx/other_planes/x-45a ucav.mdl")
	util.PrecacheModel("models/hawx/planes/av-8b harrier ii.mdl")
	util.PrecacheModel("models/hawx/planes/b-52h stratoforfress.mdl")
	util.PrecacheModel("models/hawx/planes/dassault mirage 2000 5.mdl")
	util.PrecacheModel("models/hawx/planes/dassault mirage iii.mdl")
	util.PrecacheModel("models/hawx/planes/eurofighter 2000 typhoon.mdl")
	util.PrecacheModel("models/hawx/planes/f-5a freedom fighter.mdl")
	util.PrecacheModel("models/hawx/planes/f-14a tomcat.mdl")
	util.PrecacheModel("models/hawx/planes/saab-39 gripen.mdl")
	util.PrecacheModel("models/hawx/planes/x-02 wyvern.mdl")
	util.PrecacheModel("models/hawx/planes/xa-20 razorback strike fighter.mdl")
	util.PrecacheModel("models/hawx/planes/yf-17 cobra")
	util.PrecacheModel("models/kirov/kirov.mdl")
	util.PrecacheModel("models/bf2/helicopters/mil mi-28/mil mi-28.mdl")
	util.PrecacheModel("models/bf2/helicopters/v-22 osprey/v-22 osprey.mdl")
	util.PrecacheModel("models/bf2/helicopters/v-22 osprey/v-22 osprey_rotor.mdl")
	util.PrecacheModel("models/bf2/helicopters/wz-10/wz-10.mdl")
	
end

print( "[NeuroPlanes] precache.lua loaded!" )